LogDir: /home/gonbe/var/log
Debug: false
Daemon: true

Prowl:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# ProxyHost: 
# ProxyPort:
# ProxyUser:
# ProxyPass:

Accounts:
 -
  Application: "Gonbe's Twitter"
  User: gonbe
  Pass: himitsu
  MentionsCount: 10
  MentionsInterval: 300
  MentionsPriority: 1
  DirectCount: 10
  DirectInterval: 600
  DirectPriority: 0
  RateLimitThreshold: 20
  UseProxy: false
