LogDir: /tmp
Debug: false
Daemon: true

Prowl:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# ProxyURL:

Accounts:
 -
  Application: "Twitter"
  User: example_username
  Streaming: false         # use User streams API
  RateLimitThreshold: 20
  UseProxy: false          # <= use Prowl::ProxyURL
  IgnoreSelf: true         # ignore All event by self
  SendDM: true             # send DirectMessage on Unfollowed and Membership event
  Mentions:                # Event on Mentions
    Enable: true
    Priority: 1
    Count: 10              # <= ignored when Streaming
    Interval: 300          # <= ignored when Streaming
  Direct:                  # Event on Direct Messages
    Enable: true
    Priority: 0
    Count: 10
    Interval: 600
  Retweets:                # Event on Retweets
    Enbale: true
    Priority: 0
    Count: 10              # <= ignored when Streaming
    Interval: 300          # <= ignored when Streaming
  Membership:              # Event on List Membership
    Enable: true
    Priority: 0
    Interval: 3600         # <= ignored when Streaming
  Unfollowed:              # Event on Unfollowed, requires many API rate
    Enable: true
    Priority: 0
    Interval: 1800
  Favorite:                # Event on Favorite/Unfavorite, requires Streaming.
    Enable: true
    Priority: 0
