LogDir: /tmp
Debug: false
Daemon: true
# ProxyURI:
# CAPath:

Prowl:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

NMA:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Accounts:
 -
  Application: "Twitter"
  NotifyMethods:
    - "prwol" # Prowl for iPhone
#    - "nma"  # Notify My Android for Android
  User: example_username
  RateLimitThreshold: 20
  UseProxy: false          # <= use Prowl::ProxyURL
  Mentions:                # Event on Mentions
    Enable: true
    Priority: 1
    IgnoreSelf: false      # Ignore mention by myself
  Direct:                  # Event on Direct Messages
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore DM event from myself
  Retweets:                # Event on Retweets
    Enable: true
    Priority: 0
  Membership:              # Event on List Membership
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore event by myself
    IgnoreNegative: false  # Ignore remove event
  Favorite:                # Event on Favorite/Unfavorite
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore event by myself
    IgnoreNegative: false  # Ignore Unfavorite event
  Unfollowed:              # Event on Unfollowed, requiresi API rate
    Enable: true
    Priority: 0
    Interval: 1800
  RegexpMatch:
    -
      User: "eew_jp"
      Priority: 2
      Enable: true
    -
      Text: "TwiProwl"
      Priority: 0
      Enable: true
    -
      User: "^northeye$"
      Text: "TwiProwl|twiprowl"
